print("Hello from Git")
print("Hi Charvi from Github")
print("Change from first branch")
print("Lets catch up through coding")
print("Hello from other local dir on desktop")
print("Change from first branch")
